services:
  code-server:
    image: 'lscr.io/linuxserver/code-server:latest'
    environment:
      - SERVICE_URL_CODESERVER_8443
      - PUID=1000
      - PGID=1000
      - TZ=America/Santo_Domingo
      - PASSWORD=$SERVICE_PASSWORD_64_PASSWORDCODESERVER
      - SUDO_PASSWORD=$SERVICE_PASSWORD_SUDOCODESERVER
      - DEFAULT_WORKSPACE=/config/workspace
      - NODEJS_MOD_VERSION=20
      # mods
      - DOCKER_MODS=linuxserver/mods:code-server-python3
        |linuxserver/mods:code-server-nodejs
        |linuxserver/mods:code-server-golang-1.22
    volumes:
      - code-server-config:/config
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:8443'
      interval: 2s
      timeout: 10s
      retries: 15

