services:
  jellyfin:
    image: 'lscr.io/linuxserver/jellyfin:latest'
    environment:
      - SERVICE_FQDN_JELLYFIN_8096
      - JELLYFIN_PublishedServerUrl=$SERVICE_FQDN_JELLYFIN_8096
      - PUID=1000
      - PGID=1000
      - TZ=America/Santo_Domingo
    volumes:
      - /data/jellyfin/config:/config
      - /data/jellyfin/tvshows:/data/tvshows
      - /data/jellyfin/movies:/data/movies
      - /media/nica/hdd/videos:/data/media/hdd
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:8096'
      interval: 2s
      timeout: 10s
      retries: 15
