services:
  metube:
    image: 'ghcr.io/alexta69/metube:latest'
    environment:
      - SERVICE_FQDN_METUBE_8081
      - UID=1000
      - GID=1000
      - DELETE_FILE_ON_TRASHCAN=true
    volumes:
      - '/data/metube/downloads:/downloads'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:8081'
      interval: 2s
      timeout: 10s
      retries: 15
    labels:
      - 'traefik.http.middlewares.metube.basicauth.users=<user>:<pass>'
