services:
  navidrome:
    image: deluan/navidrome:latest
    environment:
      - SERVICE_FQDN_NAVIDROME_4533
      - ND_ENABLESHARING=true
      - ND_ENABLEINSIGHTSCOLLECTOR=false
      - ND_PROMETHEUS_ENABLED=true
      - ND_PROMETHEUS_METRICSPATH=${METRICS_PATH:-/metrics___secret}
    volumes:
      - ./data:/data
      - /mnt/disk/<disk-uuid>/music:/music:ro
