services:
  netalertx:
    image: ghcr.io/jokob-sk/netalertx:latest
    network_mode: ${NETALERTX_NETWORK_MODE}
    read_only: true
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - NET_BIND_SERVICE
    volumes:
      - netalertx_data:/data
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    # Comment out to retain logs between container restarts - this has a server performance impact.
    tmpfs:
      - "/tmp:uid=20211,gid=20211,mode=1700,rw,noexec,nosuid,nodev,async,noatime,nodiratime"
    environment:
      - SERVICE_URL_NETALERTX_20211
      - NETALERTX_NETWORK_MODE=${NETALERTX_NETWORK_MODE-host}
      - LISTEN_ADDR=${LISTEN_ADDR:-0.0.0.0}
      - PORT=${PORT:-20211}
      - GRAPHQL_PORT=${GRAPHQL_PORT:-20212}
      # - NETALERTX_DEBUG=${NETALERTX_DEBUG:-0} # 0=kill all services and restart if any dies. 1 keeps running dead services.
    mem_limit: 2048m            # Maximum memory usage
    mem_reservation: 1024m      # Soft memory limit
    cpu_shares: 512             # Relative CPU weight for CPU contention scenarios
    pids_limit: 512             # Limit the number of processes/threads to prevent fork bombs
    logging:
      driver: "json-file"       # Use JSON file logging driver
      options:
        max-size: "10m"         # Rotate log files after they reach 10MB
        max-file: "3"           # Keep a maximum of 3 log files
    labels:
      - traefik.http.middlewares.authelia@file
