services:
  netalertx:
    image: 'jokobsk/netalertx:latest'
    network_mode: host
    volumes:
      - './config:/app/config'
      - './db:/app/db'
      -
        type: tmpfs
        target: /app/api
    environment:
      - SERVICE_URL_NETALERTX_20211
      - TZ=America/Santo_Domingo
      - PORT=20211
    labels:
      - traefik.http.middlewares.authelia@file
