services:
  pihole:
    image: pihole/pihole:latest
    environment:
      - SERVICE_URL_PIHOLE_80
      - TZ=America/Santo_Domingo
      - FTLCONF_webserver_api_password=${SERVICE_PASSWORD_64_PIHOLE}
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
    volumes:
      - /data/pihole/etc-pihole:/etc/pihole
      - /data/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    # https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
