services:
  transmission:
    image: 'lscr.io/linuxserver/transmission:latest'
    environment:
      - SERVICE_URL_TRANSMISSION_9091
      - PUID=1000
      - PGID=1000
      - 'USER=${SERVICE_USER_ADMIN}'
      - 'PASS=${SERVICE_PASSWORD_ADMIN}'
    volumes:
      - '/data/transmission/config:/config'
      - '/mnt/disk/<disk-uuid>/torrents/downloads:/downloads'
      - '/mnt/disk/<disk-uuid>/torrents/watch:/watch'
    healthcheck:
      test:
        - CMD
        - curl
        - '-sSfL'
        - '-u'
        - '${SERVICE_USER_ADMIN}:${SERVICE_PASSWORD_ADMIN}'
        - 'http://localhost:9091/'
      interval: 30s
      timeout: 10s
      retries: 3
