services:
  upsnap:
    image: ghcr.io/seriousm4x/upsnap:4
    network_mode: host
    restart: unless-stopped
    environment:
      - SERVICE_URL_UPSNAP_8090
    volumes:
      - upsnap-data:/app/pb_data
