services:
  wgeasy:
    image: ghcr.io/wg-easy/wg-easy:latest
    environment:
      - SERVICE_URL_WGEASY_51821
      - WG_HOST=${SERVICE_FQDN_WGEASY}
      - WG_PORT=51820
      - WG_ALLOWED_IPS=${ALLOWED_IPS:-0.0.0.0/0, ::/0, 10.0.0.0/24}
      - WG_DEFAULT_DNS=${DEFAULT_DNS:-1.1.1.1}
      - LANG=${LANG:-en}
      - WG_PASSWORD=${SERVICE_PASSWORD_ADMIN}
    volumes:
      - wireguard-data:/etc/wireguard
    ports:
      - 51820:51820/udp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    entrypoint:
      - /bin/bash
      - -c
      - |
        eval "wgpw '${WG_PASSWORD}' > /pass-hash"
        eval "$(cat /pass-hash) dumb-init node server.js"
